### ISSUE TITLE
SEO: The landing pages seem to be not indexed by Google

### ISSUE THREAD

**Issue by RobertMischke** [MemoWikis/webapp#833]
See: 
https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Amemucho.de&item_key=CAMYGCAC&hl=en

It looks like 10.6K pages are not indixed. 

acceptance criteria:
- no error in indexing anymore in the google search console

**Comment by Daniel-Majunke** [comment]
Problem Description:
Google indexes URLs with /1 at the end, e.g., memucho.de/Frage/Titel/2325/1.
Original links without /1 are recognized as duplicates and are not indexed.

Cause:
The page memucho.de/Frage/Titel/2325/1 is considered the canonical version.
The implementation seems intentional, but the exact reason is unknown.

**Comment by tj-mai** [comment]
![Image](https://github.com/MemoWikis/webapp/assets/41473684/96396f68-9ab3-4eeb-bd69-254b6b9542de)

- Alternate page with proper canonical tag
can be ignored:
Reason:
![Image](https://github.com/MemoWikis/webapp/assets/41473684/ec7009ba-2289-4c70-9ee3-66da132d4b21)

**Comment by tj-mai** [comment]
- redirects for older urls (for example urls with Fragesatz)
- update robots.txt with apiVue etc.
- restart new page crawling

- reconfirm errors with apiVue in questionlandingpage
view-source:https://memucho.de/Fragen/Wie-viele-Minuten-sind-35-Stunden/5162/1

**Comment by tj-mai** [comment]
pages that need to be indexed:
- question landingpage
- topics
- users
